# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build exam-genius-backend`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t exam-genius-backend`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system exam-genius-backend && \
          adduser --system -G exam-genius-backend exam-genius-backend

COPY dist/exam-genius-backend exam-genius-backend
RUN chown -R exam-genius-backend:exam-genius-backend .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix exam-genius-backend --omit=dev -f install

CMD [ "node", "exam-genius-backend" ]
